"""Frontend translation utilities for use in TypeScript/React.

This file provides Python utilities that generate TypeScript types
and constants for translations.
"""

import json
from pathlib import Path
from typing import Dict


def generate_translation_types() -> str:
    """Generate TypeScript types from translation files.

    Returns:
        TypeScript type definitions as a string
    """
    translations_dir = Path(__file__).parent.parent / "translations"
    translations = {}

    # Load English translations as the base
    en_file = translations_dir / "en.json"
    if en_file.exists():
        with open(en_file, "r", encoding="utf-8") as f:
            translations = json.load(f)

    def extract_keys(obj: Dict, prefix: str = "") -> list:
        """Recursively extract all translation keys."""
        keys = []
        for key, value in obj.items():
            full_key = f"{prefix}.{key}" if prefix else key
            if isinstance(value, dict):
                keys.extend(extract_keys(value, full_key))
            else:
                keys.append(full_key)
        return keys

    keys = extract_keys(translations)
    keys_union = " | ".join([f"'{key}'" for key in keys])

    ts_output = f"""// Auto-generated translation types
// DO NOT EDIT - This file is generated by the backend

export type TranslationKey = {keys_union};

export type LanguageCode = 'en' | 'fr' | 'ru' | 'ja' | 'es';

export interface Language {{
  code: LanguageCode;
  name: string;
}}

export const SUPPORTED_LANGUAGES: Language[] = [
  {{ code: 'en', name: 'English' }},
  {{ code: 'fr', name: 'Français' }},
  {{ code: 'ru', name: 'Русский' }},
  {{ code: 'ja', name: '日本語' }},
  {{ code: 'es', name: 'Español' }},
];

export const DEFAULT_LANGUAGE: LanguageCode = 'en';
"""
    return ts_output


if __name__ == "__main__":
    # Generate the types file
    output = generate_translation_types()
    frontend_path = (
        Path(__file__).parent.parent.parent
        / "frontend"
        / "lib"
        / "translations.types.ts"
    )
    frontend_path.parent.mkdir(parents=True, exist_ok=True)
    with open(frontend_path, "w", encoding="utf-8") as f:
        f.write(output)
    print(f"Generated TypeScript types at {frontend_path}")
